### ISSUE TITLE
Burp traffic doesn't show in akto UI

### ISSUE THREAD

**Issue by musana** [akto-api-security/community-edition#9]
Hi There,

Hope everything is okay. I've installed akto docker app and installed burp extension. Any traffic isn't showing in akto UI. When I checked akto burp plugin I didn't faced HTTP responses just there are requests but no response to these requests.

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/11095899/216542553-bb5fcc5b-e006-47f4-8c47-e669f147030e.png">

**Comment by avneesh-akto** [comment]
Hi @musana.

By any chance do you hv LoggerPlusPlus installed?

**Comment by musana** [comment]
Hi @avneesh-akto,

Yes, I had. I've removed loggerplusplus and the issue was fixed. In my opinion, you can mention that in FAQ. It could be helpful for new users.

Thanks.

**Comment by Ankita28g** [comment]
Thanks @musana totally! thanks a lot for your feedback. we will add it in FAQ.

**Comment by Ankita28g** [comment]
Hi @musana  thanks for your submission in Hackfest. 🔥 We are reviewing your work. Do these two below:

Join this group on [discord](https://discord.com/channels/1070706429402562733/1095281477748543618) for discussions around prizes? 🚀 🏆
Please fill this [form](https://forms.gle/fLXPKAJ8xcK9FhVP7) your PR to be considered for prizes!

**Comment by musana** [comment]
Hi @Ankita28g ,

a great idea and a great product. I wish you a continued success.

Best Regards

**Comment by Ankita28g** [comment]
@musana Add details in this form for your [swags](https://forms.gle/Nam3PVREYoMuPTNH9)

**Comment by musana** [comment]
@Ankita28g , That’s very kind of you. Most appreciated!  🎁 🥳
